name: DeepCluster Testing

on:
    push:
        branches: ["main", "staging"]
    pull_request:
        branches: ["main"]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12"]

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{matrix.python-version}}
              uses: actions/setup-python@v5
              with:
                python-version: ${{matrix.python-version}}
           
            - name: Display Python version
              run: python -c "import sys; print(sys.version)"
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install torch numpy scikit-learn
                pip install pytest pytest-cov

#            - name: Testing with pytest
#              run: pytest --cov

            - name: Testing with pytest
              run: PYTHONPATH=. pytest --cov # Since there is no setup.py, this should alternatively work as well